# 🧪 NutriTrack — Complete Test Suite

Runs all test scripts directly by importing functions from the `app/tests` directory.
- Output metrics are gathered into specific DataFrames.
- Raw data responses (p1-p4, q1-q6) are saved to `app/data/tests` for deep inspection.
- API Server is briefly spawned inside the notebook to run API endpoint tests.

## 0. Setup & Imports

In [1]:
import sys, os, time, json
import pandas as pd
from IPython.display import display

# Ensure project root is in path
project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from dotenv import load_dotenv
load_dotenv(os.path.join(project_root, "config", ".env"))

import subprocess
import requests
import time
import tests.test_api as api_tests

FAST_FOOD_IMG = os.path.join(project_root, "..", "data", "images", "food", "fast_food.jpg")
COM_TAM_IMG   = os.path.join(project_root, "..", "data", "images", "food", "com_tam.jpg")

TEST_OUTPUT_DIR = os.path.join(project_root, "data", "tests")
os.makedirs(TEST_OUTPUT_DIR, exist_ok=True)

def save_raw_output(filename: str, data: dict|list):
    if not data: return
    path = os.path.join(TEST_OUTPUT_DIR, filename)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"Saved {filename}")

print(f"✅ Setup complete. Outputs will be saved to: {TEST_OUTPUT_DIR}")

✅ Setup complete. Outputs will be saved to: d:\Project\Code\nutritrack-documentation\app\data\tests

## 1. USDA Client Tests

In [2]:
from third_apis.USDA import USDAClient
import tests.test_usda_client as usda_tests

usda_client = USDAClient(api_key=os.getenv("USDA_API_KEY"))

2026-03-06 05:45:39 | INFO     | third_apis.USDA                | USDAClient initialized (api_key=***)

In [3]:
r1 = usda_tests.test_normalize_query(usda_client)
r2 = usda_tests.test_get_PCF_mock(usda_client)
r3 = usda_tests.test_get_PCF_real(usda_client)
r4 = usda_tests.test_get_ingredients_mock(usda_client)
r5 = usda_tests.test_get_ingredients_real(usda_client)
r6 = usda_tests.test_search_best_cache(usda_client)
r7 = usda_tests.test_get_PCF_and_ingredients_mock(usda_client)
r8 = usda_tests.test_get_PCF_and_ingredients_real(usda_client)

usda_results = [r1, r2, r3, r4, r5, r6, r7, r8]
print(f"\nUSDA Client tests passed: {sum(1 for r in usda_results if r)}/{len(usda_results)}")

                           ╔════════════════════════════════════════════╗
                           ║      Starting test: _normalize_query       ║
                           ╚════════════════════════════════════════════╝
2026-03-06 05:24:21 | INFO     | tests.test_usda_client         | ✅ PASS | 'rice (gạo)' → 'rice'
2026-03-06 05:24:21 | INFO     | tests.test_usda_client         | ✅ PASS | 'bò (beef)' → 'bo'
2026-03-06 05:24:21 | INFO     | tests.test_usda_client         | ✅ PASS | 'gà (chicken)' → 'ga'
2026-03-06 05:24:21 | INFO     | tests.test_usda_client         | ✅ PASS | 'cá (fish)' → 'ca'
2026-03-06 05:24:21 | INFO     | tests.test_usda_client         | ✅ PASS | 'crème brûlée (dessert)' → 'creme brulee'
2026-03-06 05:24:21 | INFO     | tests.test_usda_client         | ✅ PASS | 'pâté (duck)' → 'pate'
2026-03-06 05:24:21 | INFO     | tests.test_usda_client         | ✅ PASS | 'spätzle (noodle)' → 'spatzle'
2026-03-06 05:24:21 | INFO     | tests.test_usda_client         | ✅ PASS | 'frühstück (breakfast)' → 'fruhstuck'
2026-03-06 05:24:21 | INFO     | tests.test_usda_client         | ✅ PASS | 'pho (vietnamese soup)' → 'pho'
2026-03-06 05:24:21 | INFO     | tests.test_usda_client         | ✅ PASS | 'fried-rice!!! (cơm chiên)' → 'fried rice'
2026-03-06 05:24:21 | INFO     | tests.test_usda_client         | ✅ PASS | 'Beef-steak' → 'beef steak'
2026-03-06 05:24:21 | INFO     | tests.test_usda_client         | ✅ PASS | '(beef)' → 'beef'
2026-03-06 05:24:21 | INFO     | tests.test_usda_client         | ✅ PASS | '() rice' → 'rice'
2026-03-06 05:24:21 | INFO     | tests.test_usda_client         | ✅ PASS | 'rice ()' → 'rice'
2026-03-06 05:24:21 | INFO     | tests.test_usda_client         | ✅ PASS | '' → ''
2026-03-06 05:24:21 | INFO     | tests.test_usda_client         | ✅ PASS | '   ' → ''
2026-03-06 05:24:21 | INFO     | tests.test_usda_client         | _normalize_query results: total=16, passed=16, failed=0

                           ╔════════════════════════════════════════════╗
                           ║   Starting test: get_PCF (mock fallback)   ║
                           ╚════════════════════════════════════════════╝
2026-03-06 05:24:21 | INFO     | third_apis.USDA                | USDA API search: query='rice'
2026-03-06 05:24:22 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'rice'
2026-03-06 05:24:22 | INFO     | third_apis.USDA                | _parse_PCF: 'RICE' (fdcId=356554, score=1000.5)
2026-03-06 05:24:22 | INFO     | tests.test_usda_client         | ✅ PASS | 'rice' → {'calories': 139.0, 'protein': 3.47, 'fat': 2.43, 'carbs': 26.4}
2026-03-06 05:24:22 | INFO     | third_apis.USDA                | USDA API search: query='grilled pork'
2026-03-06 05:24:24 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'grilled pork'
2026-03-06 05:24:24 | INFO     | third_apis.USDA                | _parse_PCF: 'GRILLED PORK' (fdcId=1913710, score=1554.0)
2026-03-06 05:24:24 | INFO     | tests.test_usda_client         | ✅ PASS | 'grilled pork' → {'calories': 126.0, 'protein': 8.28, 'fat': 4.29, 'carbs': 12.9}
2026-03-06 05:24:24 | INFO     | third_apis.USDA                | USDA API search: query=''
2026-03-06 05:24:25 | INFO     | third_apis.USDA                | USDA found 5 result(s) for ''
2026-03-06 05:24:25 | INFO     | third_apis.USDA                | _parse_PCF: 'A comprehensive characterization of phenolics, amino acids and other minor bioactives of selected honeys and identification of botanical origin markers' (fdcId=2715733, score=1.0)
2026-03-06 05:24:25 | INFO     | tests.test_usda_client         | ✅ PASS | '' → {'calories': 0.0, 'protein': 0.0, 'fat': 0.0, 'carbs': 0.0}
2026-03-06 05:24:25 | INFO     | tests.test_usda_client         | get_PCF_mock results: total=3, passed=3, failed=0

                           ╔════════════════════════════════════════════╗
                           ║     Starting test: get_PCF (real data)     ║
                           ╚════════════════════════════════════════════╝
2026-03-06 05:24:25 | INFO     | third_apis.USDA                | search_best: L1 HIT (RAM) for 'rice' → 'RICE'
2026-03-06 05:24:25 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'rice' → 'RICE'
2026-03-06 05:24:25 | INFO     | third_apis.USDA                | _parse_PCF: 'RICE' (fdcId=356554, score=1000.5)
2026-03-06 05:24:25 | INFO     | tests.test_usda_client         | ✅ PASS | 'rice' → {'calories': 139.0, 'protein': 3.47, 'fat': 2.43, 'carbs': 26.4}
2026-03-06 05:24:25 | INFO     | third_apis.USDA                | USDA API search: query='pho'
2026-03-06 05:24:26 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'pho'
2026-03-06 05:24:26 | INFO     | third_apis.USDA                | _parse_PCF: 'Soup, pho, with meat' (fdcId=2707124, score=587.3)
2026-03-06 05:24:26 | INFO     | tests.test_usda_client         | ✅ PASS | 'pho' → {'calories': 77.0, 'protein': 5.81, 'fat': 3.33, 'carbs': 5.6}
2026-03-06 05:24:26 | INFO     | third_apis.USDA                | USDA API search: query='cha lua'
2026-03-06 05:24:27 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'cha lua'
2026-03-06 05:24:27 | INFO     | third_apis.USDA                | _parse_PCF: 'Sauce, hot chile, sriracha, CHA! BY TEXAS PETE' (fdcId=171187, score=441.8)
2026-03-06 05:24:27 | INFO     | tests.test_usda_client         | ✅ PASS | 'Chả lụa' → {'calories': 108.0, 'protein': 2.02, 'fat': 0.98, 'carbs': 22.7}
2026-03-06 05:24:27 | INFO     | third_apis.USDA                | USDA API search: query='bo'
2026-03-06 05:24:28 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'bo'
2026-03-06 05:24:28 | INFO     | third_apis.USDA                | _parse_PCF: 'BOING!, GUAVA SODA, GUAVA' (fdcId=2543012, score=243.5)
2026-03-06 05:24:28 | INFO     | tests.test_usda_client         | ✅ PASS | 'bò (beef)' → {'calories': 50.0, 'protein': 0.0, 'fat': 0.0, 'carbs': 12.1}
2026-03-06 05:24:28 | INFO     | third_apis.USDA                | search_best: L1 HIT (RAM) for '' → 'A comprehensive characterization of phenolics, amino acids and other minor bioactives of selected honeys and identification of botanical origin markers'
2026-03-06 05:24:28 | INFO     | third_apis.USDA                | search_best: Cache HIT for '' → 'A comprehensive characterization of phenolics, amino acids and other minor bioactives of selected honeys and identification of botanical origin markers'
2026-03-06 05:24:28 | INFO     | third_apis.USDA                | _parse_PCF: 'A comprehensive characterization of phenolics, amino acids and other minor bioactives of selected honeys and identification of botanical origin markers' (fdcId=2715733, score=1.0)
2026-03-06 05:24:28 | INFO     | tests.test_usda_client         | ✅ PASS | '' → {'calories': 0.0, 'protein': 0.0, 'fat': 0.0, 'carbs': 0.0}
2026-03-06 05:24:28 | INFO     | tests.test_usda_client         | get_PCF_real results: total=5, passed=5, failed=0

                      ╔══════════════════════════════════════════════════════╗
                      ║   Starting test: get_ingredients (Mock/Edge cases)   ║
                      ╚══════════════════════════════════════════════════════╝
2026-03-06 05:24:28 | WARNING  | third_apis.USDA                | get_ingredients: empty query
2026-03-06 05:24:28 | INFO     | tests.test_usda_client         | ✅ PASS | empty string '' → None
2026-03-06 05:24:28 | WARNING  | third_apis.USDA                | get_ingredients: empty query
2026-03-06 05:24:28 | INFO     | tests.test_usda_client         | ✅ PASS | whitespace only '   ' → None
2026-03-06 05:24:28 | INFO     | tests.test_usda_client         | get_ingredients_mock results: total=2, passed=2, failed=0

                         ╔═══════════════════════════════════════════════╗
                         ║   Starting test: get_ingredients (Real API)   ║
                         ╚═══════════════════════════════════════════════╝
2026-03-06 05:24:28 | INFO     | third_apis.USDA                | search_best: L2 HIT (disk) for 'snickers' → 'Candies, MARS SNACKFOOD US, SNICKERS Bar'
2026-03-06 05:24:28 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'snickers' → 'Candies, MARS SNACKFOOD US, SNICKERS Bar'
2026-03-06 05:24:28 | INFO     | third_apis.USDA                | _parse_ingredient_string: no 'ingredients' for 'Candies, MARS SNACKFOOD US, SNICKERS Bar' (fdcId=169589)
2026-03-06 05:24:28 | INFO     | third_apis.USDA                | get_ingredients: 0 ingredients for 'snickers'
2026-03-06 05:24:28 | INFO     | tests.test_usda_client         | ✅ PASS | 'snickers' → None (no ingredients field — acceptable for SR Legacy)
2026-03-06 05:24:28 | INFO     | third_apis.USDA                | USDA API search: query='oreo'
2026-03-06 05:24:29 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'oreo'
2026-03-06 05:24:29 | INFO     | third_apis.USDA                | _parse_ingredient_string: no 'ingredients' for 'McDONALD'S, McFLURRY with OREO cookies' (fdcId=173304)
2026-03-06 05:24:29 | INFO     | third_apis.USDA                | get_ingredients: 0 ingredients for 'oreo'
2026-03-06 05:24:29 | INFO     | tests.test_usda_client         | ✅ PASS | 'oreo' → None (no ingredients field — acceptable for SR Legacy)
2026-03-06 05:24:29 | INFO     | third_apis.USDA                | USDA API search: query='coca cola'
2026-03-06 05:24:30 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'coca cola'
2026-03-06 05:24:30 | INFO     | third_apis.USDA                | _parse_ingredient_string: no 'ingredients' for 'Beverages, The COCA-COLA company, Minute Maid, Lemonade' (fdcId=171884)
2026-03-06 05:24:30 | INFO     | third_apis.USDA                | get_ingredients: 0 ingredients for 'coca cola'
2026-03-06 05:24:30 | INFO     | tests.test_usda_client         | ✅ PASS | 'coca cola' → None (no ingredients field — acceptable for SR Legacy)
2026-03-06 05:24:30 | INFO     | tests.test_usda_client         | get_ingredients_real results: total=3, passed=3, failed=0

                           ╔════════════════════════════════════════════╗
                           ║     Starting test: search_best caching     ║
                           ╚════════════════════════════════════════════╝
2026-03-06 05:24:30 | INFO     | third_apis.USDA                | All caches cleared (L1 + L2)
2026-03-06 05:24:30 | INFO     | third_apis.USDA                | USDA API search: query='snickers'
2026-03-06 05:24:31 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'snickers'
2026-03-06 05:24:31 | INFO     | tests.test_usda_client         | ✅ Cache populated after 1st call for 'snickers'
2026-03-06 05:24:31 | INFO     | third_apis.USDA                | search_best: L1 HIT (RAM) for 'snickers' → 'Candies, MARS SNACKFOOD US, SNICKERS Bar'
2026-03-06 05:24:31 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'snickers' → 'Candies, MARS SNACKFOOD US, SNICKERS Bar'
2026-03-06 05:24:31 | INFO     | tests.test_usda_client         | ✅ L1 Cache HIT on 2nd call — same object returned
2026-03-06 05:24:31 | INFO     | third_apis.USDA                | search_best: L1 HIT (RAM) for 'snickers' → 'Candies, MARS SNACKFOOD US, SNICKERS Bar'
2026-03-06 05:24:31 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'snickers' → 'Candies, MARS SNACKFOOD US, SNICKERS Bar'
2026-03-06 05:24:31 | INFO     | third_apis.USDA                | _parse_PCF: 'Candies, MARS SNACKFOOD US, SNICKERS Bar' (fdcId=169589, score=439.0)
2026-03-06 05:24:31 | INFO     | tests.test_usda_client         | ✅ PASS | get_PCF('snickers') also benefits from search_best cache: {'calories': 491.0, 'protein': 7.53, 'fat': 23.8, 'carbs': 61.5}
2026-03-06 05:24:31 | INFO     | third_apis.USDA                | search_best: L1 HIT (RAM) for 'snickers' → 'Candies, MARS SNACKFOOD US, SNICKERS Bar'
2026-03-06 05:24:31 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'snickers' → 'Candies, MARS SNACKFOOD US, SNICKERS Bar'
2026-03-06 05:24:31 | INFO     | third_apis.USDA                | _parse_ingredient_string: no 'ingredients' for 'Candies, MARS SNACKFOOD US, SNICKERS Bar' (fdcId=169589)
2026-03-06 05:24:31 | INFO     | third_apis.USDA                | get_ingredients: 0 ingredients for 'snickers'
2026-03-06 05:24:31 | INFO     | tests.test_usda_client         | ✅ PASS | get_ingredients('snickers') cache HIT
2026-03-06 05:24:31 | INFO     | third_apis.USDA                | search_best: L1 HIT (RAM) for 'snickers' → 'Candies, MARS SNACKFOOD US, SNICKERS Bar'
2026-03-06 05:24:31 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'snickers' → 'Candies, MARS SNACKFOOD US, SNICKERS Bar'
2026-03-06 05:24:31 | INFO     | third_apis.USDA                | _parse_PCF: 'Candies, MARS SNACKFOOD US, SNICKERS Bar' (fdcId=169589, score=439.0)
2026-03-06 05:24:31 | INFO     | third_apis.USDA                | _parse_ingredient_string: no 'ingredients' for 'Candies, MARS SNACKFOOD US, SNICKERS Bar' (fdcId=169589)
2026-03-06 05:24:31 | INFO     | third_apis.USDA                | get_PCF_and_ingredients: 'snickers' → 0 ingredients
2026-03-06 05:24:31 | INFO     | tests.test_usda_client         | ✅ PASS | get_PCF_and_ingredients('snickers') cache HIT: candies, mars snackfood us, snickers bar
2026-03-06 05:24:31 | INFO     | tests.test_usda_client         | ✅ PASS | All 3 get_* calls shared 1 API call via search_best cache for 'snickers'

                  ╔══════════════════════════════════════════════════════════════╗
                  ║   Starting test: get_PCF_and_ingredients (Mock/Edge cases)   ║
                  ╚══════════════════════════════════════════════════════════════╝
2026-03-06 05:24:31 | WARNING  | third_apis.USDA                | get_PCF_and_ingredients: empty query
2026-03-06 05:24:31 | INFO     | tests.test_usda_client         | ✅ PASS | Empty query returned None as expected
2026-03-06 05:24:31 | WARNING  | third_apis.USDA                | get_PCF_and_ingredients: empty query
2026-03-06 05:24:31 | INFO     | tests.test_usda_client         | ✅ PASS | Whitespace-only query returned None

                 ╔═══════════════════════════════════════════════════════════════╗
                 ║   Starting test: get_PCF_and_ingredients (Integration Real)   ║
                 ╚═══════════════════════════════════════════════════════════════╝
2026-03-06 05:24:31 | INFO     | third_apis.USDA                | search_best: L1 HIT (RAM) for 'snickers' → 'Candies, MARS SNACKFOOD US, SNICKERS Bar'
2026-03-06 05:24:31 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'snickers' → 'Candies, MARS SNACKFOOD US, SNICKERS Bar'
2026-03-06 05:24:31 | INFO     | third_apis.USDA                | _parse_PCF: 'Candies, MARS SNACKFOOD US, SNICKERS Bar' (fdcId=169589, score=439.0)
2026-03-06 05:24:31 | INFO     | third_apis.USDA                | _parse_ingredient_string: no 'ingredients' for 'Candies, MARS SNACKFOOD US, SNICKERS Bar' (fdcId=169589)
2026-03-06 05:24:31 | INFO     | third_apis.USDA                | get_PCF_and_ingredients: 'snickers' → 0 ingredients
2026-03-06 05:24:31 | INFO     | tests.test_usda_client         | ✅ PASS | 'snickers' → description='candies, mars snackfood us, snickers bar', PCF={'calories': 491.0, 'protein': 7.53, 'fat': 23.8, 'carbs': 61.5}, ingredients=None

USDA Client tests passed: 8/8

## 2. Qwen3VL Model Tests
Runs the 3 model inference methods directly against the test images and records metrics.

In [4]:
from models.QWEN3VL import Qwen3VL
import tests.test_qwen_client as qwen_tests

qwen = Qwen3VL()

                           ╔════════════════════════════════════════════╗
                           ║            Initializing Qwen3VL            ║
                           ╚════════════════════════════════════════════╝
2026-03-06 05:24:42 | INFO     | models.QWEN3VL                 | model=qwen.qwen3-vl-235b-a22b, region=us-east-1
2026-03-06 05:24:42 | INFO     | models.QWEN3VL                 | Qwen3VL ready! (model=qwen.qwen3-vl-235b-a22b, region=us-east-1)

In [5]:
# ─── 1 Dish Image (com_tam.jpg) ───
q1 = qwen_tests.test_analyze_food(qwen, COM_TAM_IMG, expected_min=1, label="com_tam")
q1['method'] = 'Method 1 (Converse)'
q1['image'] = 'com_tam'
save_raw_output("q1_method1_com_tam.json", q1.get("raw_output"))

q2 = qwen_tests.test_analyze_food_with_instructor(qwen, COM_TAM_IMG, expected_min=1, label="com_tam")
q2['method'] = 'Method 2 (Instructor)'
q2['image'] = 'com_tam'
save_raw_output("q2_method2_com_tam.json", q2.get("raw_output"))

q3 = qwen_tests.test_analyze_food_with_tools(qwen, COM_TAM_IMG, expected_min=1, label="com_tam")
q3['method'] = 'Method 3 (Tools)'
q3['image'] = 'com_tam'
save_raw_output("q3_method3_com_tam.json", q3.get("raw_output"))

# ─── Multi-Dish Image (fast_food.jpg) ───
q4 = qwen_tests.test_analyze_food(qwen, FAST_FOOD_IMG, expected_min=10, label="fast_food")
q4['method'] = 'Method 1 (Converse)'
q4['image'] = 'fast_food'
save_raw_output("q4_method1_fast_food.json", q4.get("raw_output"))

q5 = qwen_tests.test_analyze_food_with_instructor(qwen, FAST_FOOD_IMG, expected_min=10, label="fast_food")
q5['method'] = 'Method 2 (Instructor)'
q5['image'] = 'fast_food'
save_raw_output("q5_method2_fast_food.json", q5.get("raw_output"))

q6 = qwen_tests.test_analyze_food_with_tools(qwen, FAST_FOOD_IMG, expected_min=10, label="fast_food")
q6['method'] = 'Method 3 (Tools)'
q6['image'] = 'fast_food'
save_raw_output("q6_method3_fast_food.json", q6.get("raw_output"))

                           ╔════════════════════════════════════════════╗
                           ║      Method 1: analyze_food [com_tam]      ║
                           ╚════════════════════════════════════════════╝
2026-03-06 05:24:44 | INFO     | models.QWEN3VL                 | analyze_food() called for image: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\com_tam.jpg
2026-03-06 05:24:44 | INFO     | models.QWEN3VL                 | [Converse] Loading image: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\com_tam.jpg
2026-03-06 05:24:44 | INFO     | utils.processor                | Preparing image for Bedrock: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\com_tam.jpg
2026-03-06 05:24:44 | INFO     | models.QWEN3VL                 | [Converse] Analyzing with 'qwen.qwen3-vl-235b-a22b' → FoodList...
2026-03-06 05:24:56 | INFO     | models.QWEN3VL                 | [Converse] Successfully parsed response into FoodList
2026-03-06 05:24:56 | INFO     | tests.test_qwen_client         | Method 1 completed in 12.5s
2026-03-06 05:24:56 | INFO     | tests.test_qwen_client         | ─── Method 1 [com_tam] ───
2026-03-06 05:24:56 | INFO     | tests.test_qwen_client         |   [1] Vietnamese Pork Chop Rice (Cơm Tấm Sườn Nướng) — Cal: 680.0, Ingredients: 11
2026-03-06 05:24:56 | INFO     | tests.test_qwen_client         | ✅ PASS | Method1-com_tam: 1 items detected
Saved q1_method1_com_tam.json

                      ╔══════════════════════════════════════════════════════╗
                      ║   Method 2: analyze_food_with_instructor [com_tam]   ║
                      ╚══════════════════════════════════════════════════════╝
2026-03-06 05:24:56 | INFO     | models.QWEN3VL                 | analyze_food_with_instructor() called for image: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\com_tam.jpg
2026-03-06 05:24:56 | INFO     | models.QWEN3VL                 | [Instructor] Loading image: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\com_tam.jpg
2026-03-06 05:24:56 | INFO     | utils.processor                | Preparing image for Bedrock: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\com_tam.jpg
2026-03-06 05:24:56 | INFO     | models.QWEN3VL                 | [Instructor] Analyzing with 'qwen.qwen3-vl-235b-a22b' → FoodList...
2026-03-06 05:25:00 | INFO     | models.QWEN3VL                 | [Instructor] Successfully parsed response into FoodList
2026-03-06 05:25:00 | INFO     | tests.test_qwen_client         | Method 2 completed in 3.5s
2026-03-06 05:25:00 | INFO     | tests.test_qwen_client         | ─── Method 2 [com_tam] ───
2026-03-06 05:25:00 | ERROR    | tests.test_qwen_client         | ❌ FAIL | Method2-com_tam: expected >= 1 items, got 0
Saved q2_method2_com_tam.json

                        ╔═════════════════════════════════════════════════╗
                        ║   Method 3: analyze_food_with_tools [com_tam]   ║
                        ╚═════════════════════════════════════════════════╝
2026-03-06 05:25:00 | INFO     | third_apis.USDA                | USDAClient initialized (api_key=***)
2026-03-06 05:25:00 | INFO     | third_apis.USDA                | L1 RAM cache cleared
2026-03-06 05:25:00 | INFO     | models.QWEN3VL                 | analyze_food_with_tools() called for image: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\com_tam.jpg
2026-03-06 05:25:00 | INFO     | models.QWEN3VL                 | [ToolCalling] Loading image: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\com_tam.jpg
2026-03-06 05:25:00 | INFO     | utils.processor                | Preparing image for Bedrock: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\com_tam.jpg
2026-03-06 05:25:00 | INFO     | models.QWEN3VL                 | [ToolCalling] Sending initial request to 'qwen.qwen3-vl-235b-a22b' with 3 tools...
2026-03-06 05:25:04 | INFO     | models.QWEN3VL                 | [ToolCalling] Round 1 — stopReason: tool_use
2026-03-06 05:25:04 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF_and_ingredients(input={"food_name": "com tam"})
2026-03-06 05:25:04 | INFO     | third_apis.USDA                | USDA API search: query='com tam'
2026-03-06 05:25:05 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'com tam'
2026-03-06 05:25:05 | INFO     | third_apis.USDA                | _parse_PCF: 'TAM TAMS ONION' (fdcId=2209558, score=457.0)
2026-03-06 05:25:05 | INFO     | third_apis.USDA                | get_PCF_and_ingredients: 'com tam' → 10 ingredients
2026-03-06 05:25:05 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF_and_ingredients('com tam') → tam tams onion
2026-03-06 05:25:05 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF_and_ingredients(input={"food_name": "grilled pork chop"})
2026-03-06 05:25:05 | INFO     | third_apis.USDA                | USDA API search: query='grilled pork chop'
2026-03-06 05:25:06 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'grilled pork chop'
2026-03-06 05:25:06 | INFO     | third_apis.USDA                | _parse_PCF: 'Pork, chop, stuffed' (fdcId=2705872, score=646.1)
2026-03-06 05:25:06 | INFO     | third_apis.USDA                | _parse_ingredient_string: no 'ingredients' for 'Pork, chop, stuffed' (fdcId=2705872)
2026-03-06 05:25:06 | INFO     | third_apis.USDA                | get_PCF_and_ingredients: 'grilled pork chop' → 0 ingredients
2026-03-06 05:25:06 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF_and_ingredients('grilled pork chop') → pork, chop, stuffed
2026-03-06 05:25:06 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF_and_ingredients(input={"food_name": "fried egg"})
2026-03-06 05:25:06 | INFO     | third_apis.USDA                | USDA API search: query='fried egg'
2026-03-06 05:25:07 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'fried egg'
2026-03-06 05:25:07 | INFO     | third_apis.USDA                | _parse_PCF: 'Egg, whole, cooked, fried' (fdcId=173423, score=585.6)
2026-03-06 05:25:07 | INFO     | third_apis.USDA                | _parse_ingredient_string: no 'ingredients' for 'Egg, whole, cooked, fried' (fdcId=173423)
2026-03-06 05:25:07 | INFO     | third_apis.USDA                | get_PCF_and_ingredients: 'fried egg' → 0 ingredients
2026-03-06 05:25:07 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF_and_ingredients('fried egg') → egg, whole, cooked, fried
2026-03-06 05:25:07 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF_and_ingredients(input={"food_name": "white rice"})
2026-03-06 05:25:07 | INFO     | third_apis.USDA                | USDA API search: query='white rice'
2026-03-06 05:25:08 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'white rice'
2026-03-06 05:25:08 | INFO     | third_apis.USDA                | _parse_PCF: 'WHITE RICE' (fdcId=2488703, score=1208.0)
2026-03-06 05:25:08 | INFO     | third_apis.USDA                | get_PCF_and_ingredients: 'white rice' → 5 ingredients
2026-03-06 05:25:08 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF_and_ingredients('white rice') → white rice
2026-03-06 05:25:08 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF_and_ingredients(input={"food_name": "pickled vegetables"})
2026-03-06 05:25:08 | INFO     | third_apis.USDA                | USDA API search: query='pickled vegetables'
2026-03-06 05:25:10 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'pickled vegetables'
2026-03-06 05:25:10 | INFO     | third_apis.USDA                | _parse_PCF: 'PICKLED VEGETABLES' (fdcId=2067849, score=1473.2)
2026-03-06 05:25:10 | INFO     | third_apis.USDA                | get_PCF_and_ingredients: 'pickled vegetables' → 11 ingredients
2026-03-06 05:25:10 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF_and_ingredients('pickled vegetables') → pickled vegetables
2026-03-06 05:25:13 | INFO     | models.QWEN3VL                 | [ToolCalling] Round 2 — stopReason: tool_use
2026-03-06 05:25:13 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF(input={"food_name": "white rice"})
2026-03-06 05:25:13 | INFO     | third_apis.USDA                | search_best: L1 HIT (RAM) for 'white rice' → 'WHITE RICE'
2026-03-06 05:25:13 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'white rice' → 'WHITE RICE'
2026-03-06 05:25:13 | INFO     | third_apis.USDA                | _parse_PCF: 'WHITE RICE' (fdcId=2488703, score=1208.0)
2026-03-06 05:25:13 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF('white rice') → {'calories': 356.0, 'protein': 6.67, 'fat': 0.0, 'carbs': 80.0}
2026-03-06 05:25:13 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF(input={"food_name": "grilled pork"})
2026-03-06 05:25:13 | INFO     | third_apis.USDA                | USDA API search: query='grilled pork'
2026-03-06 05:25:14 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'grilled pork'
2026-03-06 05:25:14 | INFO     | third_apis.USDA                | _parse_PCF: 'GRILLED PORK' (fdcId=1913710, score=1554.0)
2026-03-06 05:25:14 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF('grilled pork') → {'calories': 126.0, 'protein': 8.28, 'fat': 4.29, 'carbs': 12.9}
2026-03-06 05:25:14 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF(input={"food_name": "fried egg"})
2026-03-06 05:25:14 | INFO     | third_apis.USDA                | search_best: L1 HIT (RAM) for 'fried egg' → 'Egg, whole, cooked, fried'
2026-03-06 05:25:14 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'fried egg' → 'Egg, whole, cooked, fried'
2026-03-06 05:25:14 | INFO     | third_apis.USDA                | _parse_PCF: 'Egg, whole, cooked, fried' (fdcId=173423, score=585.6)
2026-03-06 05:25:14 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF('fried egg') → {'calories': 196.0, 'protein': 13.6, 'fat': 14.8, 'carbs': 0.83}
2026-03-06 05:25:14 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF(input={"food_name": "pickled vegetables"})
2026-03-06 05:25:14 | INFO     | third_apis.USDA                | search_best: L1 HIT (RAM) for 'pickled vegetables' → 'PICKLED VEGETABLES'
2026-03-06 05:25:14 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'pickled vegetables' → 'PICKLED VEGETABLES'
2026-03-06 05:25:14 | INFO     | third_apis.USDA                | _parse_PCF: 'PICKLED VEGETABLES' (fdcId=2067849, score=1473.2)
2026-03-06 05:25:14 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF('pickled vegetables') → {'calories': 25.0, 'protein': 1.07, 'fat': 0.0, 'carbs': 6.07}
2026-03-06 05:25:14 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF(input={"food_name": "cucumber"})
2026-03-06 05:25:14 | INFO     | third_apis.USDA                | USDA API search: query='cucumber'
2026-03-06 05:25:15 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'cucumber'
2026-03-06 05:25:15 | INFO     | third_apis.USDA                | _parse_PCF: 'Cucumber salad made with cucumber and vinegar' (fdcId=2709821, score=482.3)
2026-03-06 05:25:15 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF('cucumber') → {'calories': 34.0, 'protein': 0.5, 'fat': 0.13, 'carbs': 6.79}
2026-03-06 05:25:24 | INFO     | models.QWEN3VL                 | [ToolCalling] Round 3 — stopReason: end_turn
2026-03-06 05:25:24 | INFO     | models.QWEN3VL                 | [ToolCalling] Final response received (2017 chars)
2026-03-06 05:25:24 | INFO     | models.QWEN3VL                 | [ToolCalling] Successfully parsed response into FoodList (1 items)
2026-03-06 05:25:24 | INFO     | tests.test_qwen_client         | Method 3 completed in 24.3s
2026-03-06 05:25:24 | INFO     | tests.test_qwen_client         | ─── Method 3 [com_tam] ───
2026-03-06 05:25:24 | INFO     | tests.test_qwen_client         |   [1] Com Tam (Broken Rice with Grilled Pork) (Cơm Tấm) — Cal: 520.0, Ingredients: 8
2026-03-06 05:25:24 | INFO     | tests.test_qwen_client         | ✅ PASS | Method3-com_tam: 1 items detected
Saved q3_method3_com_tam.json

                           ╔════════════════════════════════════════════╗
                           ║     Method 1: analyze_food [fast_food]     ║
                           ╚════════════════════════════════════════════╝
2026-03-06 05:25:24 | INFO     | models.QWEN3VL                 | analyze_food() called for image: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\fast_food.jpg
2026-03-06 05:25:24 | INFO     | models.QWEN3VL                 | [Converse] Loading image: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\fast_food.jpg
2026-03-06 05:25:24 | INFO     | utils.processor                | Preparing image for Bedrock: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\fast_food.jpg
2026-03-06 05:25:24 | INFO     | models.QWEN3VL                 | [Converse] Analyzing with 'qwen.qwen3-vl-235b-a22b' → FoodList...
2026-03-06 05:26:13 | INFO     | models.QWEN3VL                 | [Converse] Successfully parsed response into FoodList
2026-03-06 05:26:13 | INFO     | tests.test_qwen_client         | Method 1 completed in 48.2s
2026-03-06 05:26:13 | INFO     | tests.test_qwen_client         | ─── Method 1 [fast_food] ───
2026-03-06 05:26:13 | INFO     | tests.test_qwen_client         |   [1] Roasted Potatoes (Khoai tây nướng) — Cal: 220.0, Ingredients: 3
2026-03-06 05:26:13 | INFO     | tests.test_qwen_client         |   [2] Fried Chicken Sandwich (Bánh mì gà rán) — Cal: 520.0, Ingredients: 5
2026-03-06 05:26:13 | INFO     | tests.test_qwen_client         |   [3] Fried Chicken Pieces (Gà rán miếng) — Cal: 450.0, Ingredients: 2
2026-03-06 05:26:13 | INFO     | tests.test_qwen_client         |   [4] Margherita Pizza (Pizza Margherita) — Cal: 480.0, Ingredients: 4
2026-03-06 05:26:13 | INFO     | tests.test_qwen_client         |   [5] Beef Shawarma Wrap (Cuộn thịt bò Shawarma) — Cal: 380.0, Ingredients: 6
2026-03-06 05:26:13 | INFO     | tests.test_qwen_client         |   [6] Nachos with Cheese and Salsa (Nachos phô mai và sốt salsa) — Cal: 420.0, Ingredients: 4
2026-03-06 05:26:13 | INFO     | tests.test_qwen_client         |   [7] French Fries (Khoai tây chiên) — Cal: 320.0, Ingredients: 3
2026-03-06 05:26:13 | INFO     | tests.test_qwen_client         |   [8] Fried Chicken Nuggets (Gà rán viên) — Cal: 380.0, Ingredients: 2
2026-03-06 05:26:13 | INFO     | tests.test_qwen_client         |   [9] Grilled Cheese Quesadilla (Quesadilla phô mai nướng) — Cal: 300.0, Ingredients: 2
2026-03-06 05:26:13 | INFO     | tests.test_qwen_client         |   [10] Bacon and Egg (Thịt xông khói và trứng) — Cal: 350.0, Ingredients: 3
2026-03-06 05:26:13 | INFO     | tests.test_qwen_client         |   [11] Fried Shrimp (Tôm chiên) — Cal: 320.0, Ingredients: 2
2026-03-06 05:26:13 | INFO     | tests.test_qwen_client         |   [12] Breakfast Sandwich (Bánh mì ăn sáng) — Cal: 400.0, Ingredients: 6
2026-03-06 05:26:13 | INFO     | tests.test_qwen_client         | ✅ PASS | Method1-fast_food: 12 items detected
Saved q4_method1_fast_food.json

                     ╔════════════════════════════════════════════════════════╗
                     ║   Method 2: analyze_food_with_instructor [fast_food]   ║
                     ╚════════════════════════════════════════════════════════╝
2026-03-06 05:26:13 | INFO     | models.QWEN3VL                 | analyze_food_with_instructor() called for image: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\fast_food.jpg
2026-03-06 05:26:13 | INFO     | models.QWEN3VL                 | [Instructor] Loading image: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\fast_food.jpg
2026-03-06 05:26:13 | INFO     | utils.processor                | Preparing image for Bedrock: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\fast_food.jpg
2026-03-06 05:26:13 | INFO     | models.QWEN3VL                 | [Instructor] Analyzing with 'qwen.qwen3-vl-235b-a22b' → FoodList...
2026-03-06 05:26:17 | INFO     | models.QWEN3VL                 | [Instructor] Successfully parsed response into FoodList
2026-03-06 05:26:17 | INFO     | tests.test_qwen_client         | Method 2 completed in 4.0s
2026-03-06 05:26:17 | INFO     | tests.test_qwen_client         | ─── Method 2 [fast_food] ───
2026-03-06 05:26:17 | ERROR    | tests.test_qwen_client         | ❌ FAIL | Method2-fast_food: expected >= 10 items, got 0
Saved q5_method2_fast_food.json

                       ╔═══════════════════════════════════════════════════╗
                       ║   Method 3: analyze_food_with_tools [fast_food]   ║
                       ╚═══════════════════════════════════════════════════╝
2026-03-06 05:26:17 | INFO     | third_apis.USDA                | USDAClient initialized (api_key=***)
2026-03-06 05:26:17 | INFO     | third_apis.USDA                | L1 RAM cache cleared
2026-03-06 05:26:17 | INFO     | models.QWEN3VL                 | analyze_food_with_tools() called for image: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\fast_food.jpg
2026-03-06 05:26:17 | INFO     | models.QWEN3VL                 | [ToolCalling] Loading image: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\fast_food.jpg
2026-03-06 05:26:17 | INFO     | utils.processor                | Preparing image for Bedrock: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\fast_food.jpg
2026-03-06 05:26:17 | INFO     | models.QWEN3VL                 | [ToolCalling] Sending initial request to 'qwen.qwen3-vl-235b-a22b' with 3 tools...
2026-03-06 05:26:24 | INFO     | models.QWEN3VL                 | [ToolCalling] Round 1 — stopReason: tool_use
2026-03-06 05:26:24 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF_and_ingredients(input={"food_name": "roasted potatoes"})
2026-03-06 05:26:24 | INFO     | third_apis.USDA                | USDA API search: query='roasted potatoes'
2026-03-06 05:26:26 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'roasted potatoes'
2026-03-06 05:26:26 | INFO     | third_apis.USDA                | _parse_PCF: 'Potato, roasted, NFS' (fdcId=2709402, score=473.0)
2026-03-06 05:26:26 | INFO     | third_apis.USDA                | _parse_ingredient_string: no 'ingredients' for 'Potato, roasted, NFS' (fdcId=2709402)
2026-03-06 05:26:26 | INFO     | third_apis.USDA                | get_PCF_and_ingredients: 'roasted potatoes' → 0 ingredients
2026-03-06 05:26:26 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF_and_ingredients('roasted potatoes') → potato, roasted, nfs
2026-03-06 05:26:26 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF_and_ingredients(input={"food_name": "fried chicken sandwich"})
2026-03-06 05:26:26 | INFO     | third_apis.USDA                | USDA API search: query='fried chicken sandwich'
2026-03-06 05:26:27 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'fried chicken sandwich'
2026-03-06 05:26:27 | INFO     | third_apis.USDA                | _parse_PCF: 'Chicken fillet sandwich, fried, on wheat bun' (fdcId=2707010, score=673.0)
2026-03-06 05:26:27 | INFO     | third_apis.USDA                | _parse_ingredient_string: no 'ingredients' for 'Chicken fillet sandwich, fried, on wheat bun' (fdcId=2707010)
2026-03-06 05:26:27 | INFO     | third_apis.USDA                | get_PCF_and_ingredients: 'fried chicken sandwich' → 0 ingredients

In [6]:
qwen_results = [q1, q2, q3, q4, q5, q6]

print(f"\nQwen3VL tests passed: {sum(1 for r in qwen_results if r.get('success', False))}/{len(qwen_results)}")
print("(Note: Instructor tests are expected to fail with bedrock JSON schema)")

df_qwen = pd.DataFrame(qwen_results)
cols = ['method', 'image', 'status', 'time_s', 'dishes', 'ingredients', 'bedrock_calls', 'usda_calls', 'usda_cache_hits', 'tool_rounds', 'notes']
cols = [c for c in cols if c in df_qwen.columns]

display(df_qwen[cols].fillna(''))

Qwen3VL tests passed: 4/6
(Note: Instructor tests are expected to fail with bedrock JSON schema)

,method,image,status,time_s,dishes,ingredients,bedrock_calls,usda_calls,usda_cache_hits,tool_rounds,notes
0,Method 1 (Converse),com_tam,✅ PASS,12.5,1,11,1,0,0,0,
1,Method 2 (Instructor),com_tam,⚠️ KNOWN,3.5,0,0,1,0,0,0,BEDROCK_JSON limit / Empty results
2,Method 3 (Tools),com_tam,✅ PASS,24.3,1,8,3,7,3,3,L2 disk hits: 3
3,Method 1 (Converse),fast_food,✅ PASS,48.2,12,42,1,0,0,0,
4,Method 2 (Instructor),fast_food,⚠️ KNOWN,4.0,0,0,1,0,0,0,BEDROCK_JSON limit / Empty results
5,Method 3 (Tools),fast_food,✅ PASS,89.5,10,35,3,26,1,3,L2 disk hits: 1

## 3. Pipeline Tests
Testing the high-level orchestrated pipeline flows.

In [7]:
import tests.test_pipeline as pipeline_tests

# ─── 1 Dish Image (com_tam.jpg) ───
p1 = pipeline_tests.test_pipeline_tools(qwen, usda_client, COM_TAM_IMG, expected_min=1, label="com_tam")
p1['method'] = 'Pipeline (Tools)'
p1['image'] = 'com_tam'
save_raw_output("p1_pipeline_tools_com_tam.json", p1.get("raw_output"))

p2 = pipeline_tests.test_pipeline_manual(qwen, usda_client, COM_TAM_IMG, expected_min=1, label="com_tam")
p2['method'] = 'Pipeline (Manual)'
p2['image'] = 'com_tam'
save_raw_output("p2_pipeline_manual_com_tam.json", p2.get("raw_output"))

# ─── Multi-Dish Image (fast_food.jpg) ───
p3 = pipeline_tests.test_pipeline_tools(qwen, usda_client, FAST_FOOD_IMG, expected_min=10, label="fast_food")
p3['method'] = 'Pipeline (Tools)'
p3['image'] = 'fast_food'
save_raw_output("p3_pipeline_tools_fast_food.json", p3.get("raw_output"))

p4 = pipeline_tests.test_pipeline_manual(qwen, usda_client, FAST_FOOD_IMG, expected_min=10, label="fast_food")
p4['method'] = 'Pipeline (Manual)'
p4['image'] = 'fast_food'
save_raw_output("p4_pipeline_manual_fast_food.json", p4.get("raw_output"))

                          ╔═════════════════════════════════════════════╗
                          ║   Pipeline Test: method='tools' [com_tam]   ║
                          ╚═════════════════════════════════════════════╝
2026-03-06 05:27:47 | INFO     | third_apis.USDA                | L1 RAM cache cleared

                           ╔════════════════════════════════════════════╗
                           ║        Nutrition Analysis Pipeline         ║
                           ╚════════════════════════════════════════════╝
2026-03-06 05:27:47 | INFO     | scripts.pipeline               | Image: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\com_tam.jpg | Method: tools

                           ╔════════════════════════════════════════════╗
                           ║        Pipeline Mode: Tool Calling         ║
                           ╚════════════════════════════════════════════╝
2026-03-06 05:27:47 | INFO     | models.QWEN3VL                 | analyze_food_with_tools() called for image: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\com_tam.jpg
2026-03-06 05:27:47 | INFO     | models.QWEN3VL                 | [ToolCalling] Loading image: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\com_tam.jpg
2026-03-06 05:27:47 | INFO     | utils.processor                | Preparing image for Bedrock: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\com_tam.jpg
2026-03-06 05:27:47 | INFO     | models.QWEN3VL                 | [ToolCalling] Sending initial request to 'qwen.qwen3-vl-235b-a22b' with 3 tools...
2026-03-06 05:27:51 | INFO     | models.QWEN3VL                 | [ToolCalling] Round 1 — stopReason: tool_use
2026-03-06 05:27:51 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF_and_ingredients(input={"food_name": "com tam"})
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | search_best: L2 HIT (disk) for 'com tam' → 'TAM TAMS ONION'
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'com tam' → 'TAM TAMS ONION'
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | _parse_PCF: 'TAM TAMS ONION' (fdcId=2209558, score=457.0)
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | get_PCF_and_ingredients: 'com tam' → 10 ingredients
2026-03-06 05:27:51 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF_and_ingredients('com tam') → tam tams onion
2026-03-06 05:27:51 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF_and_ingredients(input={"food_name": "grilled pork chop"})
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | search_best: L2 HIT (disk) for 'grilled pork chop' → 'Pork, chop, stuffed'
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'grilled pork chop' → 'Pork, chop, stuffed'
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | _parse_PCF: 'Pork, chop, stuffed' (fdcId=2705872, score=646.1)
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | _parse_ingredient_string: no 'ingredients' for 'Pork, chop, stuffed' (fdcId=2705872)
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | get_PCF_and_ingredients: 'grilled pork chop' → 0 ingredients
2026-03-06 05:27:51 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF_and_ingredients('grilled pork chop') → pork, chop, stuffed
2026-03-06 05:27:51 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF_and_ingredients(input={"food_name": "fried egg"})
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | search_best: L2 HIT (disk) for 'fried egg' → 'Egg, whole, cooked, fried'
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'fried egg' → 'Egg, whole, cooked, fried'
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | _parse_PCF: 'Egg, whole, cooked, fried' (fdcId=173423, score=585.6)
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | _parse_ingredient_string: no 'ingredients' for 'Egg, whole, cooked, fried' (fdcId=173423)
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | get_PCF_and_ingredients: 'fried egg' → 0 ingredients
2026-03-06 05:27:51 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF_and_ingredients('fried egg') → egg, whole, cooked, fried
2026-03-06 05:27:51 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF_and_ingredients(input={"food_name": "white rice"})
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | search_best: L2 HIT (disk) for 'white rice' → 'WHITE RICE'
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'white rice' → 'WHITE RICE'
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | _parse_PCF: 'WHITE RICE' (fdcId=2488703, score=1208.0)
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | get_PCF_and_ingredients: 'white rice' → 5 ingredients
2026-03-06 05:27:51 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF_and_ingredients('white rice') → white rice
2026-03-06 05:27:51 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF_and_ingredients(input={"food_name": "pickled vegetables"})
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | search_best: L2 HIT (disk) for 'pickled vegetables' → 'PICKLED VEGETABLES'
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'pickled vegetables' → 'PICKLED VEGETABLES'
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | _parse_PCF: 'PICKLED VEGETABLES' (fdcId=2067849, score=1473.2)
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | get_PCF_and_ingredients: 'pickled vegetables' → 11 ingredients
2026-03-06 05:27:51 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF_and_ingredients('pickled vegetables') → pickled vegetables
2026-03-06 05:27:51 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF_and_ingredients(input={"food_name": "Vietnamese pork roll"})
2026-03-06 05:27:51 | INFO     | third_apis.USDA                | USDA API search: query='vietnamese pork roll'
2026-03-06 05:27:53 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'vietnamese pork roll'
2026-03-06 05:27:53 | INFO     | third_apis.USDA                | _parse_PCF: 'Pork, roll' (fdcId=2705883, score=644.2)
2026-03-06 05:27:53 | INFO     | third_apis.USDA                | _parse_ingredient_string: no 'ingredients' for 'Pork, roll' (fdcId=2705883)
2026-03-06 05:27:53 | INFO     | third_apis.USDA                | get_PCF_and_ingredients: 'vietnamese pork roll' → 0 ingredients
2026-03-06 05:27:53 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF_and_ingredients('Vietnamese pork roll') → pork, roll
2026-03-06 05:27:57 | INFO     | models.QWEN3VL                 | [ToolCalling] Round 2 — stopReason: tool_use
2026-03-06 05:27:57 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF(input={"food_name": "white rice"})
2026-03-06 05:27:57 | INFO     | third_apis.USDA                | search_best: L1 HIT (RAM) for 'white rice' → 'WHITE RICE'
2026-03-06 05:27:57 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'white rice' → 'WHITE RICE'
2026-03-06 05:27:57 | INFO     | third_apis.USDA                | _parse_PCF: 'WHITE RICE' (fdcId=2488703, score=1208.0)
2026-03-06 05:27:57 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF('white rice') → {'calories': 356.0, 'protein': 6.67, 'fat': 0.0, 'carbs': 80.0}
2026-03-06 05:27:57 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF(input={"food_name": "grilled pork"})
2026-03-06 05:27:57 | INFO     | third_apis.USDA                | search_best: L2 HIT (disk) for 'grilled pork' → 'GRILLED PORK'
2026-03-06 05:27:57 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'grilled pork' → 'GRILLED PORK'
2026-03-06 05:27:57 | INFO     | third_apis.USDA                | _parse_PCF: 'GRILLED PORK' (fdcId=1913710, score=1554.0)
2026-03-06 05:27:57 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF('grilled pork') → {'calories': 126.0, 'protein': 8.28, 'fat': 4.29, 'carbs': 12.9}
2026-03-06 05:27:57 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF(input={"food_name": "fried egg"})
2026-03-06 05:27:57 | INFO     | third_apis.USDA                | search_best: L1 HIT (RAM) for 'fried egg' → 'Egg, whole, cooked, fried'
2026-03-06 05:27:57 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'fried egg' → 'Egg, whole, cooked, fried'
2026-03-06 05:27:57 | INFO     | third_apis.USDA                | _parse_PCF: 'Egg, whole, cooked, fried' (fdcId=173423, score=585.6)
2026-03-06 05:27:57 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF('fried egg') → {'calories': 196.0, 'protein': 13.6, 'fat': 14.8, 'carbs': 0.83}
2026-03-06 05:27:57 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF(input={"food_name": "pickled vegetables"})
2026-03-06 05:27:57 | INFO     | third_apis.USDA                | search_best: L1 HIT (RAM) for 'pickled vegetables' → 'PICKLED VEGETABLES'
2026-03-06 05:27:57 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'pickled vegetables' → 'PICKLED VEGETABLES'
2026-03-06 05:27:57 | INFO     | third_apis.USDA                | _parse_PCF: 'PICKLED VEGETABLES' (fdcId=2067849, score=1473.2)
2026-03-06 05:27:57 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF('pickled vegetables') → {'calories': 25.0, 'protein': 1.07, 'fat': 0.0, 'carbs': 6.07}
2026-03-06 05:27:57 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF(input={"food_name": "Vietnamese pork roll"})
2026-03-06 05:27:57 | INFO     | third_apis.USDA                | search_best: L1 HIT (RAM) for 'vietnamese pork roll' → 'Pork, roll'
2026-03-06 05:27:57 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'vietnamese pork roll' → 'Pork, roll'
2026-03-06 05:27:57 | INFO     | third_apis.USDA                | _parse_PCF: 'Pork, roll' (fdcId=2705883, score=644.2)
2026-03-06 05:27:57 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF('Vietnamese pork roll') → {'calories': 329.0, 'protein': 13.07, 'fat': 28.39, 'carbs': 4.49}
2026-03-06 05:27:57 | INFO     | models.QWEN3VL                 | [ToolCalling] Tool request: get_PCF(input={"food_name": "cucumber"})
2026-03-06 05:27:57 | INFO     | third_apis.USDA                | search_best: L2 HIT (disk) for 'cucumber' → 'Cucumber salad made with cucumber and vinegar'
2026-03-06 05:27:57 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'cucumber' → 'Cucumber salad made with cucumber and vinegar'
2026-03-06 05:27:57 | INFO     | third_apis.USDA                | _parse_PCF: 'Cucumber salad made with cucumber and vinegar' (fdcId=2709821, score=482.3)
2026-03-06 05:27:57 | INFO     | models.QWEN3VL                 | [ToolCalling] ✅ get_PCF('cucumber') → {'calories': 34.0, 'protein': 0.5, 'fat': 0.13, 'carbs': 6.79}
2026-03-06 05:28:06 | INFO     | models.QWEN3VL                 | [ToolCalling] Round 3 — stopReason: end_turn
2026-03-06 05:28:06 | INFO     | models.QWEN3VL                 | [ToolCalling] Final response received (2246 chars)
2026-03-06 05:28:06 | INFO     | models.QWEN3VL                 | [ToolCalling] Successfully parsed response into FoodList (1 items)
2026-03-06 05:28:06 | INFO     | scripts.pipeline               | Tool-calling analysis complete: 1 dish(es) in 19.5s
2026-03-06 05:28:06 | INFO     | third_apis.USDA                | search_best: L1 HIT (RAM) for 'white rice' → 'WHITE RICE'
2026-03-06 05:28:06 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'white rice' → 'WHITE RICE'
2026-03-06 05:28:06 | INFO     | third_apis.USDA                | _parse_PCF: 'WHITE RICE' (fdcId=2488703, score=1208.0)
2026-03-06 05:28:06 | INFO     | third_apis.USDA                | search_best: L1 HIT (RAM) for 'grilled pork chop' → 'Pork, chop, stuffed'
2026-03-06 05:28:06 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'grilled pork chop' → 'Pork, chop, stuffed'
2026-03-06 05:28:06 | INFO     | third_apis.USDA                | _parse_PCF: 'Pork, chop, stuffed' (fdcId=2705872, score=646.1)
2026-03-06 05:28:06 | INFO     | third_apis.USDA                | search_best: L1 HIT (RAM) for 'fried egg' → 'Egg, whole, cooked, fried'
2026-03-06 05:28:06 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'fried egg' → 'Egg, whole, cooked, fried'
2026-03-06 05:28:06 | INFO     | third_apis.USDA                | _parse_PCF: 'Egg, whole, cooked, fried' (fdcId=173423, score=585.6)
2026-03-06 05:28:06 | INFO     | third_apis.USDA                | search_best: L1 HIT (RAM) for 'vietnamese pork roll' → 'Pork, roll'
2026-03-06 05:28:06 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'vietnamese pork roll' → 'Pork, roll'
2026-03-06 05:28:06 | INFO     | third_apis.USDA                | _parse_PCF: 'Pork, roll' (fdcId=2705883, score=644.2)
2026-03-06 05:28:06 | INFO     | third_apis.USDA                | search_best: L1 HIT (RAM) for 'pickled vegetables' → 'PICKLED VEGETABLES'
2026-03-06 05:28:06 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'pickled vegetables' → 'PICKLED VEGETABLES'
2026-03-06 05:28:06 | INFO     | third_apis.USDA                | _parse_PCF: 'PICKLED VEGETABLES' (fdcId=2067849, score=1473.2)
2026-03-06 05:28:06 | INFO     | third_apis.USDA                | search_best: L1 HIT (RAM) for 'cucumber' → 'Cucumber salad made with cucumber and vinegar'
2026-03-06 05:28:06 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'cucumber' → 'Cucumber salad made with cucumber and vinegar'
2026-03-06 05:28:06 | INFO     | third_apis.USDA                | _parse_PCF: 'Cucumber salad made with cucumber and vinegar' (fdcId=2709821, score=482.3)
2026-03-06 05:28:06 | INFO     | third_apis.USDA                | USDA API search: query='tomato'
2026-03-06 05:28:07 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'tomato'
2026-03-06 05:28:07 | INFO     | third_apis.USDA                | _parse_PCF: 'TOMATO' (fdcId=2293024, score=1110.3)
2026-03-06 05:28:07 | INFO     | third_apis.USDA                | USDA API search: query='green herbs'
2026-03-06 05:28:09 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'green herbs'
2026-03-06 05:28:09 | INFO     | third_apis.USDA                | _parse_PCF: 'Beverages, tea, herb, brewed, chamomile' (fdcId=174156, score=287.6)
2026-03-06 05:28:09 | INFO     | third_apis.USDA                | USDA API search: query='chili pepper'
2026-03-06 05:28:10 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'chili pepper'
2026-03-06 05:28:10 | INFO     | third_apis.USDA                | _parse_PCF: 'CHILI PEPPER' (fdcId=1919992, score=1330.7)
2026-03-06 05:28:10 | INFO     | scripts.pipeline               | Dish 'Com Tam (Broken Rice with Grilled Pork)' (Cơm Tấm) — USDA cal=1304.4, avg_cal=992.2, ingredients: 9
2026-03-06 05:28:10 | INFO     | scripts.pipeline               | Pipeline complete in 23.0s (method=tools)
2026-03-06 05:28:10 | INFO     | tests.test_pipeline            | ✅ PASS | Pipeline (tools) [com_tam]: 1 dish(es) in 23.0s
Saved p1_pipeline_tools_com_tam.json

                          ╔══════════════════════════════════════════════╗
                          ║   Pipeline Test: method='manual' [com_tam]   ║
                          ╚══════════════════════════════════════════════╝
2026-03-06 05:28:10 | INFO     | third_apis.USDA                | L1 RAM cache cleared

                           ╔════════════════════════════════════════════╗
                           ║        Nutrition Analysis Pipeline         ║
                           ╚════════════════════════════════════════════╝
2026-03-06 05:28:10 | INFO     | scripts.pipeline               | Image: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\com_tam.jpg | Method: manual

                           ╔════════════════════════════════════════════╗
                           ║       Pipeline Mode: Manual (2-step)       ║
                           ╚════════════════════════════════════════════╝

                           ╔════════════════════════════════════════════╗
                           ║      Step 1/2: Qwen3VL Image Analysis      ║
                           ╚════════════════════════════════════════════╝
2026-03-06 05:28:10 | INFO     | models.QWEN3VL                 | analyze_food() called for image: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\com_tam.jpg
2026-03-06 05:28:10 | INFO     | models.QWEN3VL                 | [Converse] Loading image: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\com_tam.jpg
2026-03-06 05:28:10 | INFO     | utils.processor                | Preparing image for Bedrock: d:\Project\Code\nutritrack-documentation\app\..\data\images\food\com_tam.jpg
2026-03-06 05:28:10 | INFO     | models.QWEN3VL                 | [Converse] Analyzing with 'qwen.qwen3-vl-235b-a22b' → FoodList...
2026-03-06 05:28:22 | INFO     | models.QWEN3VL                 | [Converse] Successfully parsed response into FoodList
2026-03-06 05:28:22 | INFO     | scripts.pipeline               | Step 1/2 complete: detected 1 dish(es) in 11.9s

                           ╔════════════════════════════════════════════╗
                           ║      Step 2/2: USDA Nutrition Lookup       ║
                           ╚════════════════════════════════════════════╝
2026-03-06 05:28:22 | INFO     | scripts.pipeline               | Processing dish 1/1: Vietnamese Pork Chop Rice (Cơm Tấm Sườn Nướng)
2026-03-06 05:28:22 | INFO     | third_apis.USDA                | search_best: L2 HIT (disk) for 'grilled pork chop' → 'Pork, chop, stuffed'
2026-03-06 05:28:22 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'grilled pork chop' → 'Pork, chop, stuffed'
2026-03-06 05:28:22 | INFO     | third_apis.USDA                | _parse_PCF: 'Pork, chop, stuffed' (fdcId=2705872, score=646.1)
2026-03-06 05:28:22 | INFO     | third_apis.USDA                | USDA API search: query='broken rice'
2026-03-06 05:28:23 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'broken rice'
2026-03-06 05:28:23 | INFO     | third_apis.USDA                | _parse_PCF: 'BROKEN WILD RICE' (fdcId=579339, score=450.3)
2026-03-06 05:28:23 | INFO     | third_apis.USDA                | search_best: L2 HIT (disk) for 'fried egg' → 'Egg, whole, cooked, fried'
2026-03-06 05:28:23 | INFO     | third_apis.USDA                | search_best: Cache HIT for 'fried egg' → 'Egg, whole, cooked, fried'
2026-03-06 05:28:23 | INFO     | third_apis.USDA                | _parse_PCF: 'Egg, whole, cooked, fried' (fdcId=173423, score=585.6)
2026-03-06 05:28:23 | INFO     | third_apis.USDA                | USDA API search: query='pork roll'
2026-03-06 05:28:24 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'pork roll'
2026-03-06 05:28:24 | INFO     | third_apis.USDA                | _parse_PCF: 'PORK ROLL' (fdcId=1931409, score=1383.6)
2026-03-06 05:28:25 | INFO     | third_apis.USDA                | USDA API search: query='pickled carrots and daikon'
2026-03-06 05:28:26 | INFO     | third_apis.USDA                | USDA found 5 result(s) for 'pickled carrots and daikon'

KeyboardInterrupt:

In [ ]:
pipe_results = [p1, p2, p3, p4]
print(f"\nPipeline tests passed: {sum(1 for r in pipe_results if r.get('success', False))}/{len(pipe_results)}")

df_pipe = pd.DataFrame(pipe_results)
pipe_cols = ['method', 'image', 'status', 'time_s', 'dishes', 'ingredients', 'bedrock_calls', 'usda_calls', 'usda_cache_hits', 'tool_rounds', 'notes']
pipe_cols = [c for c in pipe_cols if c in df_pipe.columns]

display(df_pipe[pipe_cols].fillna(''))

Pipeline tests passed: 4/4

,method,image,status,time_s,dishes,ingredients,bedrock_calls,usda_calls,usda_cache_hits,tool_rounds,notes
0,Pipeline (Tools),com_tam,✅ PASS,14.1,1,9,3,1,7,3,
1,Pipeline (Manual),com_tam,✅ PASS,23.2,1,12,1,13,11,0,
2,Pipeline (Tools),fast_food,✅ PASS,79.0,11,33,4,10,34,4,
3,Pipeline (Manual),fast_food,✅ PASS,83.6,12,46,1,1,12,0,

## 4. API Endpoint Tests
Automatically spawn the Uvicorn server, hit the endpoints, and close the server.

In [5]:
# Start fastapi server in background
print("Starting FASTAPI server in background...")
env = os.environ.copy()
server_process = subprocess.Popen(
    [sys.executable, "templates/api.py"], 
    cwd=project_root, 
    stdout=subprocess.PIPE, 
    stderr=subprocess.PIPE,
    env=env
)

Starting FASTAPI server in background...

In [ ]:
try:
    # Try hit healthcheck to confirm up
    resp = requests.get("http://localhost:8000/health", timeout=5)
    print("Server is UP.")
    
    a1 = api_tests.test_health_check()
    a2 = api_tests.test_analyze_invalid_file()
    a3 = api_tests.test_analyze_tools(COM_TAM_IMG, label="com_tam_tools", expected_min=1)
    a4 = api_tests.test_analyze_manual(COM_TAM_IMG, label="com_tam_manual", expected_min=1)

    api_results = [a1, a2, a3, a4]
    print(f"\nAPI tests passed: {sum(1 for r in api_results if r)}/{len(api_results)}")
    
except Exception as e:
    print(f"Failed during API tests: {e}")
finally:
    # Teardown server
    try:
        print("Terminating server...")
        server_process.terminate()
        server_process.wait()
        print("Server terminated.")
    except: pass

Server is UP.

                           ╔════════════════════════════════════════════╗
                           ║           API Test: GET /health            ║
                           ╚════════════════════════════════════════════╝
2026-03-06 05:00:11 | INFO     | tests.test_api                 | ✅ PASS | /health: {'status': 'ok', 'qwen_model': 'qwen.qwen3-vl-235b-a22b', 'usda_ready': True}

                         ╔═══════════════════════════════════════════════╗
                         ║   API Test: POST /analyze with invalid file   ║
                         ╚═══════════════════════════════════════════════╝
2026-03-06 05:00:13 | INFO     | tests.test_api                 | ✅ PASS | Invalid file correctly rejected (400)

                    ╔══════════════════════════════════════════════════════════╗
                    ║   API Test: POST /analyze?method=tools [com_tam_tools]   ║
                    ╚══════════════════════════════════════════════════════════╝
2026-03-06 05:00:35 | INFO     | tests.test_api                 | ✅ PASS | /analyze (tools) [com_tam_tools]: 1 dish(es) in 22.6s

                   ╔════════════════════════════════════════════════════════════╗
                   ║   API Test: POST /analyze?method=manual [com_tam_manual]   ║
                   ╚════════════════════════════════════════════════════════════╝
2026-03-06 05:01:01 | INFO     | tests.test_api                 | ✅ PASS | /analyze (manual) [com_tam_manual]: 1 dish(es) in 25.6s

API tests passed: 4/4
Terminating server...